### ISSUE TITLE
Would love to see how mutations work

### ISSUE THREAD

**Issue by nickpoorman** [rmosolgo/graphql-ruby-demo#14]
This documentation is great: https://rmosolgo.github.io/graphql-ruby/relay/mutations but I'd love to see how mutations should be done by looking in this demo app.

**Comment by rmosolgo** [comment]
Sorry, I didn't add anything right away because I didn't want to be responsible for public user input 😅  

I'll try to add one here when I get a chance, or if you see a good way to add one without sending user-provided text back to other users, feel free to add one!

**Comment by Willianvdv** [comment]
We could add a "like" to a starwars object and store the result in the session of the user.

**Comment by nickpoorman** [comment]
I would think something as simple as mutating the user input and echoing it back to them in the response would be enough.

**Comment by Oneill38** [comment]
Any chance we can get a mutation example soon? I'm trying to work through it and am having a difficult time getting one to work (specifically, without relay)
