### ISSUE TITLE
Please check Error in HeorkuServer

### ISSUE THREAD

**Issue by saroar** [rmosolgo/graphql-ruby-demo#17]
i was try your app in local its work but when i check ur app on heroku it does not work please would you like to check that is error and why 
i am new in GraphQL and Rails so i could find it yet

**Comment by Willianvdv** [comment]
Hey @saroar, can you post the error so we can see what's going on?

**Comment by saroar** [comment]
http://prntscr.com/d15zm8
this in my heroku site but you have to change your heroku logs
JSON::ParserError (776: unexpected token at 'null'):

**Comment by rmosolgo** [comment]
Looks like `null` is not a valid value for "Variables"

![image](https://cloud.githubusercontent.com/assets/2231765/19852575/8e811d3e-9f3a-11e6-8feb-648bff4e7435.png)

**Comment by saroar** [comment]
i am sorry if i dont understand is it normal ?(why its null) i mean it error from your code check your heroku logs please and could you fixed it becz we learn from your code and this error is from your code 
thanks

**Comment by rmosolgo** [comment]
To "fix" the problem, don't send `null` as the variables. Here are two solutions:
1. Delete `null` so that "Variables" is empty: 
   
   ![image](https://cloud.githubusercontent.com/assets/2231765/19852725/5735de0e-9f3b-11e6-8c65-a22141408367.png)
2. OR Replace `null` with an empty object (`{}`): 
   
   ![image](https://cloud.githubusercontent.com/assets/2231765/19852743/6c689b22-9f3b-11e6-957f-bfdff2df389b.png)

**Comment by saroar** [comment]
```
class ApiController < ApplicationController
  def new
  end

  def create
    query_string = params[:query]
    query_variables = ensure_hash(params[:variables])
    result = AmarAddaSchema.execute(
      query_string,
      variables: query_variables,
      context: {}
    )
    render json: result
  end

  private

  def ensure_hash(query_variables)
    if query_variables.blank? # then i change it blank to .present? its working fine but then blank it give my null
      {}
    elsif query_variables.is_a?(String)
      JSON.parse(query_variables)
    else
      query_variables
    end
  end
end
```

dont know why i receive query variables null the same code like your :(
in my heroku i got this error null

**Comment by saroar** [comment]
i think i got the problem thanks i solve it
