### ISSUE TITLE
Add a date type example?

### ISSUE THREAD

**Issue by AndrewRayCode** [rmosolgo/graphql-ruby-demo#27]
For a quickstart demo helper, it would be helpful for me to see how to define a date type and use it in a schema

**Comment by ghost** [comment]
Any news on this?

**Comment by itsjimmyh** [comment]
would also like to know

**Comment by rmosolgo** [comment]
Here's an example from howtographql: https://github.com/howtographql/graphql-ruby/blob/master/app/graphql/types/date_time_type.rb

**Comment by dblock** [comment]
Inspired from above.

```ruby
Types::DateType = GraphQL::ScalarType.define do
  name 'Date'

  coerce_input ->(value, _ctx) { Time.zone.parse(value).to_date }
  coerce_result ->(value, _ctx) { value.iso8601 }
end
```

**Comment by dostu** [comment]
`GraphQL::Types::ISO8601DateTime` recently got added to graphql-ruby.

Usage example:
`field :created_at, GraphQL::Types::ISO8601DateTime, null: false`

**Comment by dblock** [comment]
I think we still need a `Date`, aka not a Date+Time type, no?

**Comment by bexuma** [comment]
You could use:
`field :created_at, types.String`

Which would have the following result:
`"created_at": "2019-01-14 15:03:01 UTC"`

On your client side you could have easily tailor the resulting field to serve your very needs.
