### ISSUE TITLE
Question: Schema

### ISSUE THREAD

**Issue by wied03** [rmosolgo/graphql-ruby-demo#6]
@rmosolgo - In this demo, how does graphiql get the schema to show you on the right side bar? Does it do an implicit introspection query when it starts up?

**Comment by rmosolgo** [comment]
Yep, if you have your network tab open and reload the page, you can see it there: 

![image](https://cloud.githubusercontent.com/assets/2231765/14503644/041add46-017f-11e6-8b3c-ae343245d734.png)

![image](https://cloud.githubusercontent.com/assets/2231765/14503670/19bed15c-017f-11e6-9df2-3e53f5c4a94d.png)

**Comment by wied03** [comment]
thx
