### ISSUE TITLE
Relay Node Queries Broken?

### ISSUE THREAD

**Issue by bloomdido** [rmosolgo/graphql-ruby-demo#7]
I've been having a heck of a time over the last couple of days trying execute a Relay query to fetch a node via id. I have been able to reproduce the problem with this project (even running GraphiQL from the Heroku hosted project). Basically, if you try to execute the query located in https://github.com/rmosolgo/graphql-ruby-demo/blob/master/app/graph/queries/introQuery.graphql, you get the following error:

```
{
  "errors": [
    {
      "message": "Something went wrong during query execution: wrong number of arguments (given 2, expected 1)"
    }
  ]
}
```

In my own code, I have updated it to use the github repository for graphql-ruby instead of the gem. Now I get a different error:

```
{
  errors: [
    {
      "message": "Internal error"
    }
  ]
}
```

Not sure what is going on here. I thought I was doing something wrong, but I'm assuming the query above should work, so perhaps it's a bug?

**Comment by rmosolgo** [comment]
Thanks for the info on how to reproduce the issue. 

Oops, I failed to update this project to the new `graphql-relay` API!

Please see the update here: https://github.com/rmosolgo/graphql-ruby-demo/commit/2e99203cdd446c0300016bc58479dd9b642e35d3
