### ISSUE TITLE
Legacy file app/models/query_set.rb and app/graph/queries/ ??

### ISSUE THREAD

**Issue by bessey** [rmosolgo/graphql-ruby-demo#8]
Firstly, thank you so much for this repo, its been incredibly helpful to me. Thanks largely to this repo I've been able to get a batched GraphQL endpoint running over a rainy weekend 😄 

One thing that I didn't understand, is the `QuerySet` class legacy, or is it implicitly used somewhere? GH search doesn't show any references to it around the repo.

In addition, the files in `app/graph/queries` don't appear to be referenced by anyone besides `QuerySet`, so are these legacy too? I was under the impression that GraphQL provided a way to whitelist queries such that an internal API could not be abused to access unintended data, and wondered if it was related to this directory

**Comment by rmosolgo** [comment]
Oops, these are unused! 

Before GraphiQL was released, there was a janky query UI on this demo. Those queries were options in a `<select />`, but I guess I forgot to remove them!

> whitelist queries 

yes, this is possible ... but that's not what those are doing :P
